### ISSUE TITLE
RaspberryPi display

### ISSUE THREAD

**Issue by AdmHatena** [tsr-on-github/team2#3]
ラズパイのGUI表現は
接続性優先 -> PyQt5
処理優先 -> C++ or Electron？

(original is from tsr-on-github)

**Comment by AdmHatena** [comment]
どうせPyで作ってるし、linuxの画面表示とかやり方知らんのでPyQtでいいんでね？別にnodeにしてもいいけど（死ぬけど

**Comment by tsr-3** [comment]
pywebviewがhtml,css,javascriptで書けるらしくて，学習コストが減らせて魅力的なんだけど環境構築がわからんくて諦め
ライセンス的に PyQt < PySide (中身はほぼ同じ)なんだけどシステム開発だからライセンス問題も考慮する必要あるかも？

やりたいならnodeでどうぞ
