### ISSUE TITLE
このシステムが利用するファイルの拡張子とかどうするべ

### ISSUE THREAD

**Issue by AdmHatena** [tsr-on-github/team2#4]
というわけで意見募集

**Comment by tsr-3** [comment]
Pythonの演習でやった感じで扱いたいなら.csv
システム全体では内部的に扱いやすく.jsonを使って、最終的な出力だけ汎用的な拡張子を使うのもいいかな(処理が面倒だけど)

**Comment by AdmHatena** [comment]
ファイルフォーマットの話じゃなくてネーミングセンス（？？？）的な話だから実装上の話とかはなしで大丈夫

**Comment by tsr-3** [comment]
じゃあ僕以外の人に訊いた方がいいですね

ココじゃない方で連絡してみては？

**Comment by AdmHatena** [comment]
LINEはキミが話す場所だからなぁ

**Comment by tsr-3** [comment]
そのためにDiscordをつくったのでは？

他のチームメンバーがどう思ってるかは私には分かりかねますが

**Comment by Fukuda-B** [comment]
how about ".bson" ?

**Comment by AdmHatena** [comment]
> how about ".bson"

This file is a deliberately encrypted json file, and it is preferable to use a name that makes it impossible to identify the original file format. Also, "B" is very bad and should be avoided in the name.
