### ISSUE TITLE
Raspberry Pi と教員PCの接続手法は？？？

### ISSUE THREAD

**Issue by tsr-3** [tsr-on-github/team2#5]
案ください

**Comment by tsr-3** [comment]
Raspberry Pi <---> 教員PC
SSH接続 で通信内容（通信路）暗号化かな？

Pythonで起動時シェルスクリプトをごり押し起動 -> 無線アクセスポイント化 -> 擬似的同一ネットワークでファイル送受信

セキュリティ的な安全性は分からん

**Comment by AdmHatena** [comment]
今回の実装だと教員PCとRaspberryPi間のファイルの移動手段は完全に利用者に丸投げする方式やで
だからわざわざファイルを暗号化しようとしとるわけ

**Comment by tsr-3** [comment]
知らない間に決まってたのかなるほど完全理解
(知らない間っていうか、そんな感じの案を言ってたのは知ってるけどチーム内で確定させることまではしてなかったよね)

つまり教員PCでは暗号化されたファイルを見ることができればよいってことか

**Comment by AdmHatena** [comment]
ま？もう鯖使わない時点でこれに決まってたと思ってたわ
というか逆にそうじゃない場合はどやって接続をサポートするのさ？

**Comment by tsr-3** [comment]
上に書いた方法は技術的にできない見込み？
GUIから「接続」ボタンでも置いといてスクリプト実行させればいいかと思ってたのは甘かったかな？

ネットワーク上のフォルダからファイルを引っ張ってこれるようにすればいいんかと思ってたけど
ラズパイと教員PC間の通信路あるいは通信内容の暗号化が技術的に難しいならやめとこう

**Comment by AdmHatena** [comment]
> GUIから「接続」ボタンでも置いといてスクリプト実行させればいいかと思ってたのは甘かったかな？

すくなくともラズパイが回線に接続されている前提になるし、electronからSSHとかマジやり方わからん

> ラズパイと教員PC間の通信路あるいは通信内容の暗号化が技術的に難しいならやめとこう

ファイルそのものを暗号化はしようとしてるからそれでいいってんならいけるが

**Comment by tsr-3** [comment]
> すくなくともラズパイが回線に接続されている前提になるし、electronからSSHとかマジやり方わからん

ラズパイを教員PCのアクセスポイントにするつもりだった
electronの中身がnode.jsであることを考えると、node.jsでsshする方法と同じようにやると予想され？
調べても分からなかったら諦めるつもり
